### ISSUE TITLE
Issue with storage module.

### ISSUE THREAD

**Issue by Gonzih** [yast/yast-ruby-bindings#123]
Hi guys, after few updates I realized that modules that use Storage module are broken. Here is debug output when I'm trying to run BootLoader module:

```
2014-07-30 15:41:59 <0> max-suse(25537) [libycp] pathsearch.cc(find):310 ... success
2014-07-30 15:41:59 <0> max-suse(25537) [Y2Ruby] binary/Y2CCRuby.cc(provideNamespace):74 Find module result: '/usr/share/YaST2/modules/Storage.rb'
2014-07-30 15:41:59 <0> max-suse(25537) [Y2Ruby] binary/Y2CCRuby.cc(provideNamespace):80 returning existing ruby component
2014-07-30 15:41:59 <0> max-suse(25537) [liby2] Y2ComponentBroker.cc(getNamespaceComponent):173 Component 0x1c8b2d0 used for namespace Storage
2014-07-30 15:41:59 <0> max-suse(25537) [libycp] Import.cc(import):101 Component found: ruby
2014-07-30 15:41:59 <3> max-suse(25537) [Interpreter] yast/i18n.rb:83 No table associated to module 'Storage'
2014-07-30 15:41:59 <3> max-suse(25537) [Ruby] binary/Yast.cc(getNs):64 ruby call: Can't import namespace 'Storage'
2014-07-30 15:41:59 <3> max-suse(25537) [Ruby] yast/wfm.rb:86 Client call failed with component cannot import namespace 'Storage' and backtrace ["/usr/lib64/ruby/vendor_ruby/2.0.0/yast/yast.rb:146:in `import_pure'", "/usr/lib64/ruby/vendor_ruby/2.0.0/yast/yast.rb:146:in `import'", "/usr/share/YaST2/include/bootloader/routines/section_widgets.rb:26:in `initialize_bootloader_routines_section_widgets'", "/usr/lib64/ruby/vendor_ruby/2.0.0/yast/yast.rb:120:in `include'", "/usr/share/YaST2/include/bootloader/routines/dialogs.rb:33:in `initialize_bootloader_routines_dialogs'", "/usr/lib64/ruby/vendor_ruby/2.0.0/yast/yast.rb:120:in `include'", "/usr/share/YaST2/include/bootloader/routines/wizards.rb:27:in `initialize_bootloader_routines_wizards'", "/usr/lib64/ruby/vendor_ruby/2.0.0/yast/yast.rb:120:in `include'", "/usr/share/YaST2/clients/bootloader.rb:29:in `main'", "/usr/share/YaST2/clients/bootloader.rb:294:in `<top (required)>'", "/usr/lib64/ruby/vendor_ruby/2.0.0/yast/wfm.rb:84:in `eval'", "/usr/lib64/ruby/vendor_ruby/2.0.0/yast/wfm.rb:84:in `run_client'"]
2014-07-30 15:41:59 <0> max-suse(25537) [Ruby] yast/wfm.rb:103 Unloading client class BootloaderClient
2014-07-30 15:41:59 <1> max-suse(25537) [liby2] genericfrontend.cc(main):778 Finished YaST2 component 'y2base'
2014-07-30 15:41:59 <1> max-suse(25537) [liby2] genericfrontend.cc(main):783 Exiting with client return value 'false'
2014-07-30 15:41:59 <0> max-suse(25537) [agent-ini] IniParser.cc(write):942 File /etc/sysconfig/console did not change. Not saving.
2014-07-30 15:41:59 <0> max-suse(25537) [agent-system] SystemAgent.cc(remove_directory):99 Removing temporary file /tmp/YaST2-25537-uts4mz/exit
2014-07-30 15:41:59 <0> max-suse(25537) [agent-system] SystemAgent.cc(remove_directory):99 Removing temporary file /tmp/YaST2-25537-uts4mz/stderr
2014-07-30 15:41:59 <0> max-suse(25537) [agent-system] SystemAgent.cc(remove_directory):99 Removing temporary file /tmp/YaST2-25537-uts4mz/stdout
2014-07-30 15:41:59 <0> max-suse(25537) [agent-system] SystemAgent.cc(remove_directory):99 Removing temporary file /tmp/YaST2-25537-uts4mz
2014-07-30 15:41:59 <0> max-suse(25537) [Pkg] Y2CCPkg.cc(~Y2CCPkg):64 ~Y2CCPkg
2014-07-30 15:41:59 <0> max-suse(25537) [Pkg] PkgModule.cc(destroy):101 Deleting PkgModule object...
2014-07-30 15:41:59 <0> max-suse(25537) [Pkg] Callbacks.cc(~CallbackHandler):1903 Deleting callback handler
2014-07-30 15:41:59 <0> max-suse(25537) [Y2Ruby] binary/Y2RubyComponent.cc(~Y2RubyComponent):44 Destroying Y2RubyComponent
2014-07-30 15:41:59 <1> max-suse(25537) [Y2Ruby] binary/YRuby.cc(~YRuby):107 Shutting down ruby interpreter.
2014-07-30 15:41:59 <1> max-suse(25537) [Y2Perl] YPerl.cc(destroy):164 Shutting down embedded Perl interpreter.

```

Any tips? Thanks!

**Comment by jreidinger** [comment]
fixed by https://github.com/yast/yast-yast2/commit/330aa7ed7c83288fb53cc5acebe050c9232c3b32
thanks for report. If it still persist, please reopen with fresh logs. Thanks
