### ISSUE TITLE
SIGABRT is raised when term initialized incorrectly

### ISSUE THREAD

**Issue by mchf** [yast/yast-ruby-bindings#127]
e.g. this should do it:

```
a = term(term(:Whitespace))
SCR.RegisterAgent(path(".a"), a)
```

**Comment by mvidner** [comment]
Yes, and I see nothing in y2log:
```console
irb(main):001:0> require "yast"
in=> true
irb(main):002:0> include Yast
=> Object
irb(main):003:0> a = term(term(:Whitespace))
=> #<Yast::Term:0x00000001a23a90 @value=#<Yast::Term:0x00000001a23b08 @value=:Whitespace, @params=[]>, @params=[]>
irb(main):004:0> SCR.RegisterAgent(path(".a"), a)
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_S_construct null not valid
Neúspěšně ukončen (SIGABRT)
```

**Comment by mvidner** [comment]
Now it fails properly:
```console
Traceback (most recent call last):
        3: from -e:1:in `<main>'
        2: from /usr/lib64/ruby/vendor_ruby/2.5.0/yast/scr.rb:72:in `RegisterAgent'
        1: from /usr/lib64/ruby/vendor_ruby/2.5.0/yast/scr.rb:113:in `call_builtin_wrapper'
/usr/lib64/ruby/vendor_ruby/2.5.0/yast/scr.rb:113:in `call_builtin': wrong argument type Yast::Term (expected Symbol) (TypeError)
```
